### PR TITLE
Added log1p gpu

### PR DESCRIPTION
**Pull request by indradenbakker**

### CODE REVIEW

**Comment by iamtrask** [comment]
hmmm - GPU tests are failing - it's having a hard time finding the shader - not sure what's up yet

**Comment by iamtrask** [comment]
It's possible that i merged it wrong - here's a PR with how i merged https://github.com/OpenMined/OpenMined/tree/indradenbakker-add-log1p-gpu

**Comment by indradenbakker** [comment]
@iamtrask The GPU tests were already failing at the Travis build for PR #196, so I think it's not related to this PR.

**Comment by indradenbakker** [comment]
Merged latest master and added some fixes. All tests are passing locally and with Travis now.

**Comment by emregoynugur** [comment]
Looks great and everything seems to be fine! 

I was wondering if inline operation should be a part of this PR for completeness. CPU implementation doesn't have that too. 

Actually, I noticed that some of the ops don't have an inline version (self modifying one). Do we have a guide that shows which inline ops are necessary or not?

**Comment by indradenbakker** [comment]
The inline operations are mentioned as separate issues in PySyft. For example, for log1p we have #514 and #513. I think the idea behind this is too keep all PRs as simple as possible.

**Pull request merged**
