### PR TITLE
Feature/relu

### PR DESCRIPTION
**Pull request by yanndupis**
Hello,

It's work in progress, I have started to work on a ReLU layer. I am really not sure about the Autograd/ backward section. I will continue to work on this tomorrow.

Sorry couldn't find how to add the label work in progress.

Thanks

### CODE REVIEW

**Comment by iamtrask** [comment]
Nice! This is great! Backprop isn't too complex here either. Since the forward prop is piecewise like so:
(for each element in a vector you run the function)
def relu(x):
   if(x > 0):
         return x
   else:
         return 0

Backprop is also piecewise... for each element in a vector you run.

def relu_backprop(x):
    if(relu_output > 0):
         return 1
    else
         return 0

**Comment by yanndupis** [comment]
Great, thanks @iamtrask ! Let me try this!

**Comment by iamtrask** [comment]
Merged conflicts for ya :)

**Comment by yanndupis** [comment]
sorry @iamtrask I had some issues with this branch. I have created a new one and did a PR.

**Pull request closed without merging**
