### PR TITLE
added integration tests

### PR DESCRIPTION
**Pull request by bendecoste**
these live in the `integration/` dir under root.  There are only ones
written for `abs` right now but we can add more over time.

https://github.com/OpenMined/PySyft/issues/633

### CODE REVIEW

**Comment by diegoalejogm** [comment]
Cool, this is a great idea. We should be able to run them automatically by also sunning the Unity app automatically. Have you thought about this?

**Comment by diegoalejogm** [comment]
Though I would strongly suggest to move these tests to PySyft

**Comment by bendecoste** [comment]
> Cool, this is a great idea. We should be able to run them automatically by also sunning the Unity app automatically. Have you thought about this?

Yes was going to look into that next.

> Though I would strongly suggest to move these tests to PySyft

I don't disagree. However since the unity app is required for these to run and there is already lots of code depending on pysyft being available in this environment I put them here

**Comment by bendecoste** [comment]
You could also argue that they are integration tests for Openmined moreso than pysyft .. openmined is the black box under test

**Comment by iamtrask** [comment]
+1 to both thoughts @bendecoste  and @diegoalejogm

**Comment by diegoalejogm** [comment]
You’re right. Let’s leave them on OpenMined and move ignore we find a strong reason to.

**Comment by diegoalejogm** [comment]
Good job!

**Pull request merged**
