### PR TITLE
Fix for log1p gpu kernel

### PR DESCRIPTION
**Pull request by indradenbakker**

### CODE REVIEW

**Comment by bosr** [comment]
Thanks for reacting so quickly!!!

**Comment by diegoalejogm** [comment]
Hey @indradenbakker, I was reviewing your GPU test implementation and data is never moved to GPU.

This is done using `tensor.Gpu(shader)`. 

Check out any other test to see how it works and message me (diegoalejogm) in Slack if you have doubts!

**Comment by diegoalejogm** [comment]
Hey @indradenbakker   

I've fixed the GPU tests file, it contained the wrong functionality. You can check how to implement GPU tests now!

I also removed the missing Kernel implementation, since the GPU build was broken. 

Very sorry for the inconvenient

**Comment by indradenbakker** [comment]
Thanks @diegoalejogm !

**Pull request closed without merging**
