### PR TITLE
Added Log1p to FloatTensor (#513)

### PR DESCRIPTION
**Pull request by indradenbakker**
Added Log1p implementation, including unit test and integration test (Issue #513).

### CODE REVIEW

**Comment by gavinuhma** [comment]
great job @indradenbakker

**Comment by indradenbakker** [comment]
Thanks @gavinuhma!

**Comment by bosr** [comment]
@indradenbakker @gavinuhma 

Ooopsy 😉 you forgot to implement the GPU kernel but you declared it. So the build is broken on master ;) Without GPU tests on this kernel, this will not get detected.

Can you implement please it? (if you don't feel like it, tell it, and we'll get it done, no pb!)

Good work anyway
Cheers

**Comment by indradenbakker** [comment]
Ah yes, good one. I'll create a new PR for it. Thanks for pointing it out @bosr !

**Pull request merged**
