### PR TITLE
integration tests on travis

### PR DESCRIPTION
**Pull request by bendecoste**

### CODE REVIEW

**Comment by iamtrask** [comment]
Very excited to see if this passes!

**Comment by bendecoste** [comment]
> Very excited to see if this passes!

gotta make sure it can fail first!

**Comment by diegoalejogm** [comment]
Hey @bendecoste you can try running travis on your own fork instead, which may be faster since there are multiple runs on this repo.

**Comment by diegoalejogm** [comment]
Did it pass travis? I can't find them anywhere

**Comment by bendecoste** [comment]
They're just running on a forked repo currently ... 

I had an unexpected problem, osx images don't support python language so i can't easily run pytest or pip install it.  Have been working through that problem but feedback takes like an hour so it's pretty slow going.

**Comment by diegoalejogm** [comment]
Alright, I can wait 👍  BTW it is possible to run travis local containers, so you can test immediately. My internet is very slow atm so I can't share the link

**Comment by bendecoste** [comment]
cool will check it out, i have been letting it run and doing other stuff recently .. I'll try to buckle down and get it sorted sometime today

**Comment by bendecoste** [comment]
it takes over 25 minutes to setup an osx machine to be able to run the tests :(

**Comment by iamtrask** [comment]
yikes! that's intense!

**Comment by bendecoste** [comment]
Closing this .. 

to recap, the main problem is that travis doesn't support OSX images with the necessary python dependencies to run these tests.  Trying to install all the required ones put the build into the 30+ minute territory.

Another avenue to explore is to rewrite the install unity script to work in linux then you should be able to use a python environment.

**Comment by bendecoste** [comment]
https://github.com/OpenMined/OpenMined/issues/192

**Pull request closed without merging**
