### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by jeremyjordan**
Added integration tests to `integration/tests.py`. 

We now have coverage of `abs()` through `fmod()` with the exception of `add()`, `div()`, and `tan2()`. I wasn't sure if we are going to write functions for `add()` and `div()` since we have `__add__` and `__truediv__`, and I'm not familiar with the `tan2()` function. 

I also created a notebook that I used to generate the expected results from the analogous operation in PyTorch. 

Current tests status:
```
==================== 16 failed, 15 passed in 346.75 seconds ====================
```

Many of the failed tests are due to not being implemented yet, this should serve as a handy checklist to see what still needs to be done.

### CODE REVIEW

**Comment by gavinuhma** [comment]
looks good. waiting for ci :)

**Comment by jeremyjordan** [comment]
if the remaining tests haven't yet been written for the math operations i can handle that this weekend. 

should we consider breaking `tests.py` out into `test_mathops.py` etc. as more tests are built?

**Comment by diegoalejogm** [comment]
@jeremyjordan Well done implementing all these tests! 👍 Your idea of splitting tests sounds good too.

**Comment by diegoalejogm** [comment]
I am getting some errors:
screen shot 2017-12-11 at 22 26 31

Is anyone else getting them too when running the tests?

**Comment by diegoalejogm** [comment]
Some of the test errors are:

`AttributeError: 'FloatTensor' object has no attribute 'addcdiv'`
`AttributeError: 'FloatTensor' object has no attribute 'log1p'`
`AttributeError: 'FloatTensor' object has no attribute 'addcmul'`

**Comment by jeremyjordan** [comment]
yes, that is because those math operations haven't yet been implemented.

**Comment by diegoalejogm** [comment]
Oh okay! I get your initial comment now!

**Comment by jeremyjordan** [comment]
i went ahead and wrote the tests because my understanding is we want to mirror the functionality of a tensor in PyTorch, so by going ahead and writing all of the tests we can check which ones still need work

**Comment by diegoalejogm** [comment]
NVM my comments then. Good job thinking about the future and implementing these tests! 

I'd move them later on to a different file when we add Travis again, since it wouldn't build the project with non-implemented funcs.

**Comment by diegoalejogm** [comment]
There's still some errors non-related to the undefined functions, can you check them out @jeremyjordan ?

Here's a screenshot of some:

screen shot 2017-12-11 at 22 35 54

**Comment by jeremyjordan** [comment]
hmm let me take a look, it appears someone has contributed additional tests as i don't recall writing `test_round()`. the error with that test is the values in `expected` are being passed as a list. it should read:

`expected = np.array([value1, value2, ...])`

**Comment by jeremyjordan** [comment]
any `AttributeError` can more or less be read as `NotImplementedError`

**Comment by iamtrask** [comment]
@jeremyjordan gets a standing ovation for writing tests for functionality we have yet to implement... Super excited about this!!!

**Comment by jeremyjordan** [comment]
> if the remaining tests haven't yet been written for the math operations i can handle that this weekend.

didn't have time to get to it this past weekend, but should be able to soon.

**Pull request merged**
