### PR TITLE
Added Log() to FloatTensor

### PR DESCRIPTION
**Pull request by saru95**
Adding a binding to PySyft as well.

### CODE REVIEW

**Comment by bosr** [comment]
Hi @saru95, great!

Ooopsy, you forgot to implement the GPU kernel but you declared it. If the current PR gets merged, it will break the build. It's the same story than for `Log1p` in https://github.com/OpenMined/OpenMined/pull/183

Good work anyway!
Cheers

**Comment by saru95** [comment]
Let me give it a try. I'll let you know. :)

**Comment by bosr** [comment]
Thanks! 

Feel free also to have a look at current other PRs as Diego pointed out there that in gpu tests you have to move data to the gpu for the actual gpu code to be called! Just saying ;)

Cheers

**Comment by diegoalejogm** [comment]
Hey @saru95  

I've fixed the GPU tests file, it contained the wrong functionality. You can check how to implement GPU tests now!

Very sorry for the inconvenient

**Pull request closed without merging**
