### PR TITLE
add FloatTensor ceil function

### PR DESCRIPTION
**Pull request by abe732**

### CODE REVIEW

**Comment by abe732** [comment]
This maps to the PySyft Pull Request #631

**Comment by abe732** [comment]
This was something I went back and forth on, and the documentation on ceil is a bit vague in C# and HLSL. Actually think your right after looking into it further at other language documentation that it should be int as float and not casted. Will update and re-commit.

**Comment by abe732** [comment]
Yeah, I think you're right. I looked more into the documentation on ceil for C# and HLSL, and a couple other languages. C# returns a double, which is why you need the casting there. And HLSL returns a floating point so that should be okay without a cast. Pytorch doesn't specify the value, so I originally read it a too explicitly as needing to cast as an int. Testing out Pytorch and it also return values as float. The above fix makes ours consistent w/ pytorch.

**Comment by iamtrask** [comment]
Excellent job sir!!!

**Pull request merged**
