### PR TITLE
IntTensor.Equal(),ProcessMessage()

### PR DESCRIPTION
**Pull request by Agent007**
# Description

`equal` case in `ProcessMessage()` didn't need to create two tensor local variables

Fixes https://github.com/OpenMined/PySyft/issues/790

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

`IntTensorTest.Equal()` was already defined, so it was simply re-run to ensure there were no breaking changes.

- [x] `IntTensorTest.Equal()`

**Test Configuration**:
* CPU:
* GPU:
* PySyft Version:
* Unity Version:
* OpenMined Unity App Version:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gavinuhma** [comment]
Nice catch @Agent007 !

**Comment by Agent007** [comment]
Side note: The growing list of case statements in `IntTensor.ProcessMessage()` seems like a code smell, especially as more and more functions get added to PySyft. Is there a plan to address it? Anyway, a related PySyft PR (https://github.com/OpenMined/PySyft/pull/1289) is also ready for review.

**Comment by gavinuhma** [comment]
@Agent007 definitely. a dictionary or enum has been thrown around instead of the giant case. lots of things we need to move to `BaseTensor` too

**Comment by gavinuhma** [comment]
https://github.com/OpenMined/OpenMined/issues/354

**Pull request merged**
