### PR TITLE
Format C# files on pre-commit hook

### PR DESCRIPTION
**Pull request by adamrainsby**
Might be worth having a few people try this out before merging.
It works for me on my Mac but haven't tested it on Linux. I think it should work on Linux.
It would be cool if we could add windows support too.

### CODE REVIEW

**Comment by bendecoste** [comment]
this is great, i think we should use whatever we decide here: https://github.com/OpenMined/OpenMined/issues/149

I'd personally be happy with opening braces on same line and 4 space indents but .NET style is probably the way to go for a C# project

**Comment by adamrainsby** [comment]
@bendecoste Yeah agreed. I'll update it later to use .NET conventions.

**Comment by diegoalejogm** [comment]
@adamrainsby Do you mean later in this commit? or is this ready?

**Comment by adamrainsby** [comment]
I'll update this PR

**Pull request closed without merging**
