### PR TITLE
Remove tensor from the creators list of its children when a tensor is deleted

### PR DESCRIPTION
**Pull request by daviddemeij**
Small addition to https://github.com/OpenMined/OpenMined/pull/374 to make sure when a tensor is deleted it's not only deleted from the children_indices of its creator(s) but also deleted as a creator for its children.

### CODE REVIEW

**Comment by iamtrask** [comment]
looks like a possible bad merge


Assets/OpenMined/Syft/NN/Loss/Loss.cs(21,34): warning CS0114: `OpenMined.Syft.Layer.Loss.Loss.ProcessMessageAsLayerOrLoss(OpenMined.Network.Utils.Command, OpenMined.Network.Controllers.SyftController)' hides inherited member `OpenMined.Syft.Layer.Model.ProcessMessageAsLayerOrLoss(OpenMined.Network.Utils.Command, OpenMined.Network.Controllers.SyftController)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword

**Comment by daviddemeij** [comment]
That's weird I did a merge just before the PR, but it should be good now!

**Comment by daviddemeij** [comment]
Maybe it fails because the current master branch has compilation errors in Unity (at least for me it has)

**Comment by justin1121** [comment]
I think this can be merged now, I fixed that warning above :D

**Pull request merged**
