### PR TITLE
Speedup/mm

### PR DESCRIPTION
**Pull request by Floev**
# Description

Complete what has been started in #378
Should have solved what was fixed in #386
Hope creating no new issues
Note: loading params the weight will appear transposed, this is what gives the speedup.

On the side, I have regrouped the unit tests. Hope you folks like it?

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Added tests for an existing feature

# Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by iamtrask** [comment]
Man! Very excited about your optimization work lately sir! Just did a merge conflict and I'll wait for tests to complete before merging to master. Great work!

**Comment by iamtrask** [comment]
Humbug - I think I messed up the merge. Might need some help figuring this out - but i'll take another crack when the integration tests are done.

Great chatting with you on the underground yesterday!

**Comment by iamtrask** [comment]
Hey @Floev  - can i get your help on these merge conflicts?

**Comment by Floev** [comment]
Hey @trask, was busy with DIY this weekend. Will try to take a look Tuesday
evening!

On 3 Feb 2018 16:56, "iamtrask" <notifications@github.com> wrote:

Hey @Floev <https://github.com/floev> - can i get your help on these merge
conflicts?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/OpenMined/OpenMined/pull/390#issuecomment-362833341>,
or mute the thread

**Comment by Floev** [comment]
@iamtrask should be done!

**Comment by iamtrask** [comment]
Woot woot!

**Pull request merged**
