### PR TITLE
Added sign_(), the inline version of sign() as per issue #581

### PR DESCRIPTION
**Pull request by moodlep**
Hi there, this is related to a PR in PySyft with the same name for the same issue #581. Thanks.

### CODE REVIEW

**Comment by gavinuhma** [comment]
@moodlep could you take a look at the merge conflicts? A big change to inline functions (#129) was merged ahead of this

**Comment by moodlep** [comment]
@gavinuhma yes I saw that; sure I will take a look later today.

**Comment by moodlep** [comment]
@gavinuhma I think this is ready to go... let me know if any problems.

**Comment by diegoalejogm** [comment]
Looks good, let's wait for travis to finish

**Comment by gavinuhma** [comment]
thanks @moodlep !

**Pull request merged**
