### PR TITLE
New feature/neg 

### PR DESCRIPTION
**Pull request by moodlep**
Inline version of neg function added, as per issue #540

### CODE REVIEW

**Comment by emregoynugur** [comment]
Nice job! 

But, it looks like GPU and CPU tests are the same or am I missing something? It should be a quick fix.

**Comment by iamtrask** [comment]
Actually... @emregoynugur ... i just noticed that that's the case for all of the GPU tests... seems that none of them are actually running on the GPU.

**Comment by iamtrask** [comment]
I fixed the GPU test issue since it was a part of a broader class of issues introduced by another PR. 

Great work Perusha!!!!

**Comment by moodlep** [comment]
Oh that's cool - thanks @iamtrask !

**Pull request merged**
