### PR TITLE
Fixing GPU operations and Adding all GPU Tests

### PR DESCRIPTION
**Pull request by diegoalejogm**

### CODE REVIEW

**Comment by bosr** [comment]
Awesome!

**Comment by diegoalejogm** [comment]
Thanks! Still on its way, there's so many operations already, it is exciting tho

**Comment by bosr** [comment]
"Houston, we have lost control of the Diego rocket, we can't stop it anymore" 😆 

👍 👍 👍

**Comment by diegoalejogm** [comment]
To skip GPU tests on Travis I wasn't able to pass any params to the Unity app, so I had to create a script to delete the file directly. Though the application supports sending arguments through command line, they don't work. 

More info:
https://answers.unity.com/questions/1436131/command-line-test-runner-option-editortestscategor.html?childToView=1440854#answer-1440854

**Comment by diegoalejogm** [comment]
Tests can be filtered by category: "CPU" or "GPU".
screen shot 2017-12-09 at 22 15 29
Make sure to select the `OpenMinedMain` asset for the GPU tests to work!

**Comment by iamtrask** [comment]
Whew!!!! What a monstor!!!

**Pull request merged**
