### PR TITLE
Separated message's function process to new method. Using SWITCH stat…

### PR DESCRIPTION
**Pull request by diegoalejogm**
…ement now.

### CODE REVIEW

**Comment by diegoalejogm** [comment]
Alright, fixed tabulation errors and updated with latest Tensor Functions

**Comment by iamtrask** [comment]
got some merge conflicts i'll need to set time aside to sort - love the switch statement though - i'm also intrested in potentially moving the "processMessage" functionality for each class INTO that class - i.e., moving most of this functionality ot a "processMessage" within FloatTensor itself - thoughts?

**Comment by diegoalejogm** [comment]
Sounds good to me. The Syft Controller doesn't need to know what functions the Tensor has already. I'd love to discuss how many Tensor classes we're going to create first, so that we can figure the best way to implement such method, that all Tensors (and maybe other classes) will have.

**Comment by iamtrask** [comment]
This was a really, really nice PR! It cleans up the code so nicely. Great job @diegoalejogm

**Pull request merged**
