### PR TITLE
fixed two bugs with view and added tests for view

### PR DESCRIPTION
**Pull request by justin1121**
closes https://github.com/OpenMined/OpenMined/issues/195
closes https://github.com/OpenMined/OpenMined/issues/194

Made some changes to some of the GPU code for view as well, let me know
if that doesn't make sense.

### CODE REVIEW

**Comment by gavinuhma** [comment]
@justin1121 and @emregoynugur are talking about this so not ready to merge yet

**Comment by iamtrask** [comment]
@justin1121 and @emregoynugur  - still chatting? I like the improvements this issue makes already.

**Comment by justin1121** [comment]
I think we wanted to discuss it with others how this should be implemented. I'm good with how this is right now, its definitely an improvement and we can always change it in the future. Not sure what else @emregoynugur had in mind though.

**Comment by emregoynugur** [comment]
I agree with everything Justin just said :)

**Pull request merged**
