### PR TITLE
Autograd/sum

### PR DESCRIPTION
**Pull request by justin1121**
Not a bad first implementation for autograd sum. Once we're able to support non-contiguous tensors a lot of the code can just be replaced with a view and an expand.

### CODE REVIEW

**Comment by iamtrask** [comment]
Great job learning how the new autograd system - as it's got some more complexity, we need a couple extra unit tests. For each test, we want to try 3 things.

1. Test whether the basic backprop functionality works when the function is used in isolation. You've already implemented this! Looks great!
2. Test whether repeatedly calling forward and backprop on the function allocates new tensors (after the first forward/backprop it shouldn't). You can use the "allow_new_tensors" variable in ctrl to test this. 
3. Test whether calling backprop when sum is used correctly backprops into previous variables. While this might seem like it naturally extends from (1), if backprop is done incorrectly, it'll break. 

Because autograd fails silently, having all three of these tests (especially 2 and 3) is super important for all our variables. Would you be so kind as to add (2) and (3) to this before I merge? For an example of how it works, feel free to check out the current unit tests for Autograd in FloatTensorAutograd.cs.

**Comment by justin1121** [comment]
Sure thing! I started putting tests in another place. I can move them to where you put them as well.

**Comment by iamtrask** [comment]
Going ahead and merging this for now because I need it for another feature :)

**Comment by iamtrask** [comment]
Still hoping to see those autograd tests :)

**Pull request merged**
