### PR TITLE
Fix formatting for c# files

### PR DESCRIPTION
**Pull request by adamrainsby**
I think the inconsistent formatting was caused by MonoDevelop and maybe
some other editors not handling windows line endings (\r\n) and unix
style line endings (\n) consistently.
I used the auto-formatting feature on MonoDevelop to fix the formatting.
You can format a file by pressing CTRL + i (on mac).
The settings for formatting can be found in:
  Project > Solution Options > Source Code > Formatting > Text file
I kept all the settings as default except I changed line endings to Unix

### CODE REVIEW

**Comment by adamrainsby** [comment]
I'll rebase

**Comment by bendecoste** [comment]
👍

**Comment by adamrainsby** [comment]
No conflicts now

**Comment by iamtrask** [comment]
So purrrty!

**Comment by diegoalejogm** [comment]
Awesome. We should figure out how to have this standard in all other IDEs

**Comment by bendecoste** [comment]
Rider has project-wide settings that we can use to force everyone being on the same page.

**Comment by adamrainsby** [comment]
Maybe we could format the code in a pre-commit hook with something like https://github.com/uncrustify/uncrustify

I was hoping it would be possible to have a standard formatter that can run on save in all the text editors and IDEs people are likely to use but I can only see a atom integration with `atom-beautify`.

**Comment by adamrainsby** [comment]
First cut at a pre-commit hook https://github.com/OpenMined/OpenMined/commit/5ebbfcdb0b524956163232eb6ede2fba7e6f5746

**Pull request merged**
