### PR TITLE
Created a new constructor with shader.

### PR DESCRIPTION
**Pull request by emregoynugur**
Updated the copy op.

### CODE REVIEW

**Comment by emregoynugur** [comment]
I don't understand what you mean. There is still a constructor that can be used with a shader.

**Comment by iamtrask** [comment]
Right - but many of the functions require you to create a new FloatTensor object in which to store the result of a function - in which case you must choose which constructor to use. This PR swaps out the ones that accept a "shader" in the constructor with ones that do not - which means that now there's no way for those tensors to link to the shader at all

**Comment by emregoynugur** [comment]
That was intentional. When GPU method is selected, the op directly returns whatever GPU implementation returns. So, why don’t we use the constructor with the shader option inside the gpu implementation? GPU implementations should create their own FloatTensor (result) object.

**Comment by emregoynugur** [comment]
I see your point too. Maybe we should define one static shader and we should set that shader if host supports Compute Shaders.

**Comment by iamtrask** [comment]
Either of these options should work great!

**Comment by emregoynugur** [comment]
Updated. How does it look now?

**Comment by iamtrask** [comment]
Merged but it seems that this approach doesn't successfuly link kernels

**Comment by iamtrask** [comment]
let's try to address this in a hangout - but not tonight... bit too late as it's probably a pretty big project.

**Comment by iamtrask** [comment]
https://github.com/OpenMined/OpenMined/pull/107 - this was my attempt at a merge.

**Pull request closed without merging**
