### PR TITLE
Add ReLU layer v2

### PR DESCRIPTION
**Pull request by yanndupis**
Hello,

This PR should add a ReLU layer. I have created a notebook with a ReLU example but we can deleted later. 

Thanks,

### CODE REVIEW

**Comment by justin1121** [comment]
Hey @yanndupis this looks awesome! Just a heads up, in another branch I just deleted the AutogradTest.cs file and put all the tests in that into the FloatTensorAutogradTest.cs.

**Comment by yanndupis** [comment]
Thanks @justin1121 ! sorry for the basic Github question: what's the easiest way to delete the AutogradTest.cs file from this PR? thanks

**Comment by justin1121** [comment]
No worries! I think you should just be able to delete the file in whatever IDE youre using and then push an update to the branch or git rm <filename> from command line and then push an update.

**Comment by yanndupis** [comment]
Thanks, it seems to have worked!

**Comment by iamtrask** [comment]
Restarting the build - i believe the errors were from master just checking first

**Comment by iamtrask** [comment]
Great looking issue! One small tweak in the ReLU grad. I noticed you created the new tensor using the following.

var gradInput = output.emptyTensorCopy();

If you instead use

var gradInput = output.Copy();
gradInput.Zero_();

then when you call forward and backward repeatedly, it'll know to use the same variables in memory :)

**Comment by yanndupis** [comment]
Thanks for your review and feedbacks! it should use now the same variables in memory :)

**Comment by iamtrask** [comment]
Ballin! Great work!!

**Comment by yanndupis** [comment]
Thank you!

**Pull request merged**
