### PR TITLE
Feature: add Rsqrt_ to Float Tensor (#573)

### PR DESCRIPTION
**Pull request by yanndupis**
Hello,

This should fix [https://github.com/OpenMined/PySyft/issues/573](url)

Thank you!

### CODE REVIEW

**Comment by gavinuhma** [comment]
@yanndupis can you take a look at the conflicts? looks good otherwise

**Comment by indradenbakker** [comment]
@yanndupis Looks great! The only thing is that your integration test looks incorrect, you're comparing `expected` with `b.to_numpy()`. However, there is no `b` when using inline so I think it should be `a.to_numpy()`. 

It's also incorrect for the Exp inline integeration test, I'll make a small PR for that.

**Comment by yanndupis** [comment]
Thank you @gavinuhma and @indradenbakker for your review.

@gavinuhma - the conflicts should be fixed now. 

@indradenbakker - good catch, thank you. If you don't mind doing a small PR, that would be great

**Comment by yanndupis** [comment]
I still have conflicts. we have made significant changes since I submitted this pull request. Let me close it and re-open another one. 
Thanks

**Pull request closed without merging**
